spring: 
  profiles:
    active:
      - dev

--- 
spring:
  profiles: dev   #dev enviroment
  application:
    name: microservicecloud-config-vincent-dev

---
spring:
  profiles: dev  #testing enviroment
  application:
    name: microservicecloud-config-vincent-test